<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <AssemblyName>sim2</AssemblyName>
    <RootNamespace>Sim2</RootNamespace>
  </PropertyGroup>
</Project>
